### ISSUE TITLE
取得URL, 如何备案？

### ISSUE THREAD

**Issue by jesusjsc** [sgxiang/pdd-coupon#4]
取得URL, 如何备案呀？
打开了url，但是查询还是没有备案呀！

![image](https://user-images.githubusercontent.com/4392829/102631598-e3509980-4188-11eb-965e-2fff777289c3.png)
![image](https://user-images.githubusercontent.com/4392829/102631753-15fa9200-4189-11eb-9f38-524d7055ae3a.png)

**Comment by sgxiang** [comment]
备案的接口不需要传custom parameters，之后用手机打开响应的url授权一下
